### PR TITLE
Task/list muvis

### LINKED ISSUE #7: Koin - Crashes when activity opened multiple times
```
2019-07-06 19:56:30.740 8477-8477/com.muvi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.muvi, PID: 8477
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.muvi/com.muvi.film_detail.FilmDetailActivity}: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one: [type:Factory,primary_type:'com.muvi.film_detail.FilmDetailViewModel']
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2883)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4726)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one: [type:Factory,primary_type:'com.muvi.film_detail.FilmDetailViewModel']
        at org.koin.core.registry.BeanRegistry.addDefinition(BeanRegistry.kt:144)
        at org.koin.core.registry.BeanRegistry.saveDefinition(BeanRegistry.kt:101)
        at org.koin.core.registry.BeanRegistry.saveDefinitions(BeanRegistry.kt:71)
        at org.koin.core.registry.BeanRegistry.loadModules(BeanRegistry.kt:49)
        at org.koin.core.KoinApplication.loadModulesAndScopes(KoinApplication.kt:66)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:60)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:44)
        at org.koin.core.context.GlobalContextKt.loadKoinModules(GlobalContext.kt:86)
        at com.muvi.film_detail.FilmDetailActivity.onCreate(FilmDetailActivity.kt:35)
        at android.app.Activity.performCreate(Activity.java:7013)
        at android.app.Activity.performCreate(Activity.java:7004)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2883) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4726) 
        at android.app.ActivityThread.-wrap18(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857) 
```

### PR DESCRIPTION
**Pull request by ataulm**
Adds a RecyclerView so we can scroll through a list of movies.

Fixes #7 - discussion there on approach taken to fix, can adjust later if we want.

device-2019-07-07-202903

### CODE REVIEW

File: actor_detail/src/main/java/com/muvi/actor_detail/ActorDetailModule.kt [hunk 1]
```diff
@@ -7,7 +7,7 @@ import com.muvi.actor_detail_domain.GetActorDetailUseCase
 import org.koin.androidx.viewmodel.dsl.viewModel
 import org.koin.dsl.module
 
-val actorDetailModule = module {
+val actorDetailModule = module(override = true) {
```
Comment (ataulm) [inline actor_detail/src/main/java/com/muvi/actor_detail/ActorDetailModule.kt]: This is the change for #7

File: feed/src/main/java/com/muvi/feed/FeedFragment.kt [hunk 2]
```diff
@@ -29,14 +29,12 @@ internal class FeedFragment : Fragment() {
...
-        val button = firstFilmButton
-        feedViewModel.films.observe(this, Observer<FilmSummary> { film ->
-            film?.let {
-                button.text = film.title
-                button.setOnClickListener {
-                    startActivity(intent("com.muvi.film_detail.FilmDetailActivity", film.id))
-                }
-            }
+        val adapter = FilmSummaryAdapter {
+            startActivity(intent("com.muvi.film_detail.FilmDetailActivity", it.id))
```
Comment (ataulm) [inline feed/src/main/java/com/muvi/feed/FeedFragment.kt]: I think the VM should be deciding what happens on click. Either the VM should be emitting a list of UiModels each of which has a lambda `click`, OR the fragment should be delegating to the VM here.

Either way, the VM is the one that needs to either trigger the navigation directly or emit a single-use-event to tell the view to navigate.

File: feed/src/main/java/com/muvi/feed/FilmSummaryAdapter.kt [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+import androidx.recyclerview.widget.DiffUtil
+import androidx.recyclerview.widget.ListAdapter
+import androidx.recyclerview.widget.RecyclerView
+import com.muvi.base_domain.FilmSummary
+
+internal class FilmSummaryAdapter(private val onClick: (FilmSummary) -> Unit) : ListAdapter<FilmSummary, FilmSummaryAdapter.ViewHolder>(Differ) {
+
+    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int) = LayoutInflater.from(parent.context)
+            .inflate(R.layout.item_film_summary, parent, false)
+            .run { ViewHolder(this) }
```
Comment (ataulm) [inline feed/src/main/java/com/muvi/feed/FilmSummaryAdapter.kt]: no, I didn't need to :sweat_smile: there's like a million different ways you can do this with run, apply, let etc :grimacing: I think this is a legit way -> `run` returns the _result_ (last line) of its lambda.

but then with `let` it's similar - except it's a receiver parameter instead of `this` :thinking: I need one of those comparison sites, where you can pick two of this extension functions and see them head-to-head.

File: feed/src/main/java/com/muvi/feed/FeedFragment.kt (hunk 2 above)
Comment (hitherejoe) [reply feed/src/main/java/com/muvi/feed/FeedFragment.kt]: yea this seems like a mixed thing in the community. I would opt for the single-use-event or some stream of navigation events (for example, if multiple navigations can happen for a single screen) but could be good to look into standard ways of doing this

File: feed/src/main/java/com/muvi/feed/FilmSummaryAdapter.kt (hunk 3 above)
Comment (hitherejoe) [reply feed/src/main/java/com/muvi/feed/FilmSummaryAdapter.kt]: Yea they are pretty much the same I think, with the only difference of `let` being used to contain that local scoped variable of `it`.
